option(ONS_VITA_FIOS "Use Sony stdio/FIOS for immutable game asset reads" ON)
option(ONS_VITA_SCELIBC_MEMCPY "Route external memcpy calls to sceClibMemcpy" ON)
if(ONS_VITA_FIOS)
  find_program(ONS_VITA_LIBS_GEN vita-libs-gen HINTS "${VITASDK}/bin" REQUIRED)
  find_program(ONS_STUB_MAKE make NO_CMAKE_FIND_ROOT_PATH REQUIRED)
  set(ONS_SONY_STUB_DIR "${CMAKE_CURRENT_BINARY_DIR}/sony-stdio-stubs")
  set(ONS_SONY_STUB "${ONS_SONY_STUB_DIR}/libOnsSonyStdio_stub.a")
  add_custom_command(OUTPUT "${ONS_SONY_STUB}"
    COMMAND "${ONS_VITA_LIBS_GEN}" "${CMAKE_CURRENT_SOURCE_DIR}/platform/vita/fios/nids.yml" "${ONS_SONY_STUB_DIR}"
    COMMAND "${CMAKE_COMMAND}" -E env "VITASDK=${VITASDK}" "${ONS_STUB_MAKE}" -C "${ONS_SONY_STUB_DIR}"
    DEPENDS platform/vita/fios/nids.yml VERBATIM)
  add_custom_target(ons_sony_stdio_stubs DEPENDS "${ONS_SONY_STUB}")
  add_dependencies(onscripter_vita ons_sony_stdio_stubs)
  target_sources(onscripter_vita PRIVATE platform/vita/fios/fios.c platform/vita/sony_io.cpp)
  target_compile_definitions(onscripter_vita PRIVATE ONS_VITA_FIOS)
  target_link_libraries(onscripter_vita PRIVATE "${ONS_SONY_STUB}" SceFios2_stub)
endif()
if(ONS_VITA_SCELIBC_MEMCPY)
  target_sources(onscripter_vita PRIVATE platform/vita/sony_memcpy.c)
  target_compile_definitions(onscripter_vita PRIVATE ONS_VITA_SCELIBC_MEMCPY)
  foreach(ONS_COPY_CALL memcpy __aeabi_memcpy __aeabi_memcpy4 __aeabi_memcpy8)
    target_link_options(onscripter_vita PRIVATE "-Wl,--wrap=${ONS_COPY_CALL}")
  endforeach()
endif()
